### ISSUE TITLE
Clean up your Code

### ISSUE THREAD

**Issue by geoperez** [MarcoLPR/JavaScript#2]
Remove unnecessary code as:

* Invertir function and DarValor
* console.log outside question

Change scope (learn about scope: https://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope/)

* Make global Reversal function

Improve code quality

* Change to a global function the callback parameter at question (https://nodejs.org/api/readline.html#readline_rl_question_query_callback)

If you need help, ask me.

**Comment by MarcoLPR** [comment]
I didn't understand what were you asking for in the "Improve code quality" section.

**Comment by geoperez** [comment]
Create a global function QuestionHandler with all the code inside the arrow function.

For example:

randomMethod('argument', (a) => {
 console.log(a);
});

change to:

function handler(a) {
 console.log(a);
}

randomMethod('argument', handler);

**Comment by MarcoLPR** [comment]
You haven't told me what is an arrow function, maybe we can discuss it tomorrow

**Comment by geoperez** [comment]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions
