### ISSUE TITLE
Learn about npm

### ISSUE THREAD

**Issue by geoperez** [MarcoLPR/JavaScript#3]
Lear about npm (https://docs.npmjs.com/getting-started/what-is-npm) and create a 'package.json' file for your repository.

**Comment by MarcoLPR** [comment]
Rdy

**Comment by geoperez** [comment]
Add chalk (https://www.npmjs.com/package/chalk) as dependency to your package and use it freely.

**Comment by MarcoLPR** [comment]
Rdy
